//
//  ConstantStrings.swift
//  AirBag
//
//  Created by Geek on 8/15/18.
//  Copyright © 2018 Geek. All rights reserved.
//

import Foundation
struct  ConstantStrings{
    
    static let emailLabel = "Email"
    static let emailLabelPlace = "email@example.com"
    static let passwordLabel = "Password"
    static let firstName = "First Name"
    static let lastName = "Last Name"
    static let confirmPAss = "Confirm Password"
    static let phone = "Mobile Phone"
    static let creditCard = "Optional(Credit Card)"
    static let numberOfTravels = "Optional(Number of traves)"
    static let chooseUser = "Choose User Type"
    static let login = "Login"
    static let register = "Register"
    static let dontHaveAccout = "Don't have account!"
    static let carrier = "Carrier"
    static let sender = "Sender"
    static let reciever = " Reciever"
    static let beCarrier = "Be a Carrier"
    static let beSender = "Be a Sender"
    static let beReciever = "Be a Reciever"
    static let logOut = "Logout"
    static let notifications = "Notifications"
    static let registerationTitle = "Register new account"
    static let countries = "Choose Country"
    static let pleaseWait = "Please wait.."
    static let deparCountry = "Choose Favorite Departure Country "
    static let destCountry = "Choose Favorite Destination Country"
    static let chooseCayegory = "Choose Categories"
    static let chooseAddress = "Choose Address"
    static let mobile = "Mobile Phone"
    static let typeAddress = "Address"
    static let typePhone = "Mobile Phone"
    static let passwordPlaceHolder = "Password must be Minimum 8 characters, at least 1 Uppercase and Lowercase Alphabet, 1 Number and 1 Special Character"
    static let showPassword = "Show"
    static let  psddwordDoesntMAtch = "Password doesn't match!"
    static let  passwordWrong = "Wrong password!"
    static let  pleaseFillRequired = "Please Fill Required!"
    static let  wrongNum = "Wrong Number!"
    static let  emailVAid = "Please enter valid Email!"
    static let  countryCode = "Country code"
    static let  fillRequiredAddress = "Please fill required Departure, Destination and Address Feilds!"
     static let  chooseCategories = "Please choose categories!"
    static let successfulyReg = "Successfully Registered!"
    static let main = "Main"
    static let menu = "Menu"
    static let reservation = "Reservations"
      static let transactions = "Transactions"
    
    static let departureText = "Departure"
    static let DestinationText = "Destination"
    static let dateText = "Departure Date"
    static let timeText = "Time"
    static let availableWeightText = "Available Weight"
    static let pricePerKg = "Price Per Kg"
    static let pricePerM3 = "Price Per M3"
    static let flightNumber = "Flight Number"
    static let airLine = "Air Line"
    static let departureMob = "Departure Mobile"
    static let restrictedCategories = "Restricted Categories"
    static let bookBag = "Book Bag"
     static let yes = "Yes"
     static let no = "No"
     static let confirmLogout = "Are you sure you want to logout?"
    static let confirm = "Confirm"
    static let reserveBag = "Reserve Bag"
    static let airLines = "Airlines"
    static let airBAg = "Bag"
    static let sealBagConfirm = "Are you sure you want to seal this bag?"
    static let bagSealedSuccess =  "Your bag has been sealed successfully!"
    static let sessionExpired = "Sessios Expired, please login again!"
    static let pleaseSeal = "Please seal this bag first, before adding a new one!!"
}
